server:
  port: 8080
  servlet:
    context-path: /oliolishop
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB
    encoding:
      enabled: true
      charset: UTF-8
      force: true

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/olioli
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:12345}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          # Đảm bảo Hibernate sử dụng múi giờ Việt Nam khi lưu/đọc ngày giờ
          # từ database.
          time_zone: Asia/Ho_Chi_Minh
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:nguyenquocvuong12321@gmail.com}
    password: ${MAIL_PASSWORD:ugpk bfcy qodk dsqm}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  mvc:
    charset: UTF-8
    http:
      encoding:
        charset: UTF-8
        enabled: true
        force: true

app:
  image-dir: ${IMAGE_DIR:D:/HocTap/AI/crawl/images}
  fast-api:
    base-url: http://${FAST_API_HOST:0.0.0.0}:${FAST_API_PORT:8000}
    agent-url: http://${FAST_API_HOST:0.0.0.0}:${AGENT_PORT:8001}/api/chat

ghn:
  token: ${GHN_TOKEN:de1ce88f-9f3a-11f0-bdaf-ae7fa045a771}
  shop-id: ${SHOP_ID:197548}

jwt:
  signerKey: ${JWT_PRIVATE_KEY:c248f3c5b1e84f8d1198d01488ee23a18360ce904c9eae484072de278cf2b6cc}
